name: Check pull request workflow

on: [pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: yarn type-check

      - name: Check linting
        run: yarn lint

      - name: Check tests
        run: yarn test
